import { getAuth } from 'firebase/auth';
import type { NextPage } from 'next';
import Head from 'next/head';
import { AuthProvider, useFirebaseApp } from 'reactfire';
import { FeatureRating } from '../components/FeatureRating';
import { UserLogin } from '../components/UserLogin';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const app = useFirebaseApp(); // a parent component contains a `FirebaseAppProvider`
  const auth = getAuth(app);

  return (
    <AuthProvider sdk={auth}>
      <div className={styles.container}>
        <Head>
          <title>Vote for new features!</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <UserLogin />
        <h1 className={styles.title}>Leeroy Jenkins Voting App</h1>
        <FeatureRating />
      </div>
    </AuthProvider>
  );
};

export default Home;
